c_compiler:  # [win]
- vs2015  # [win]
cxx_compiler:  # [win]
- vs2015  # [win]

channel_sources:
  - conda-forge,ryanvolz/label/prerelease,ryanvolz,pkgw-forge,defaults

channel_targets:
  - ryanvolz prerelease
