{% set version = "3.7.12.0" %}

package:
  name: gnuradio
  version: {{ version }}

source:
#  url: https://gnuradio.org/releases/gnuradio/gnuradio-{{ version }}.tar.gz
  url: https://github.com/gnuradio/gnuradio/archive/v{{ version }}.tar.gz
  sha256: 20bb08263fb934c3474b20bd55e58b9324782b5a18cdb3f7bb5150276fcb5ceb

build:
  number: 0
  skip: True  # [win]
  detect_binary_files_with_prefix: True
  features:
    - vc14  # [win]

requirements:
  build:
    - boost 1.66.0
    - cheetah
    - cmake >=3.2
    - fftw
    - jom  # [win]
    - libusb >=1
    - log4cpp
    #- mako >=0.4.2  # will be required to replace Cheetah in an upcoming version
    - numpy
    - pkg-config  # [not win]
    - python >=2.7,<3
    - swig >=2.0.4
    - toolchain
    - vc 14  # [win]
    - volk >=1.4
  # documentation
    #- doxygen
    #- graphviz
    #- sphinx
  # testing
    #- cppunit
  # gnuradio.audio
    - alsa-lib  # [linux]
    - portaudio  # [not osx]
  # gnuradio.comedi
    #- comedi
  # gnuradio companion
    #- lxml
    #- pygtk
  # gnuradio ctrlport
    #- thrift
    #- thrift-cpp
  # gnuradio.qtgui
    - pyqt >=4,<5
    - qwt >=5.2,<=6.2.0
  # gnuradio.uhd
    - uhd 3.11.0.*
  # gnuradio.video_sdl
    #- sdl2
  # gnuradio.wxgui
    - wxpython
  # gnuradio.wavelet
    #- gsl
  # gnuradio.zeromq
    #- cppzmq
    #- zeromq

  run:
    - boost 1.66.0
    - cheetah
    - fftw
    - libusb >=1
    - log4cpp
    #- mako >=0.4.2  # will be required to replace Cheetah in an upcoming version
    - numpy
    - python >=2.7,<3
    - vc 14  # [win]
    - volk >=1.4
  # gnuradio.audio
    - alsa-lib  # [linux]
    - portaudio  # [not osx]
  # gnuradio.comedi
    #- comedi
  # gnuradio companion
    #- lxml
    #- pygtk
  # gnuradio ctrlport
    #- thrift
    #- thrift-cpp
  # gnuradio.qtgui
    - pyqt >=4,<5
    - qwt >=5.2,<=6.2.0
  # gnuradio.uhd
    - uhd 3.11.0.*
  # gnuradio.video_sdl
    #- sdl2
  # gnuradio.wxgui
    - wxpython
  # gnuradio.wavelet
    #- gsl
  # gnuradio.zeromq
    #- pyzmq
    #- zeromq

test:
  commands:
    - conda inspect linkages -p $PREFIX gnuradio  # [not win]
    - conda inspect objects -p $PREFIX gnuradio  # [osx]

  imports:
    - gnuradio.analog
#    - gnuradio.atsc
    - gnuradio.audio
    - gnuradio.blocks
    - gnuradio.channels
#    - gnuradio.comedi
    - gnuradio.digital
#    - gnuradio.dtv
#    - gnuradio.fcd
#    - gnuradio.fec
    - gnuradio.fft
    - gnuradio.filter
    - gnuradio.gr
#    - gnuradio.noaa
#    - gnuradio.pager
    - gnuradio.qtgui
#    - gnuradio.trellis
    - gnuradio.uhd
#    - gnuradio.video_sdl
#    - gnuradio.vocoder
#    - gnuradio.wavelet
    - gnuradio.wxgui
#    - gnuradio.zeromq
    - pmt

about:
  home: http://gnuradio.org/
  license: GPL-3.0
  license_file: COPYING
  summary: 'The free and open software radio ecosystem'
  description: |
    GNU Radio is a free software development toolkit that provides the signal
    processing runtime and processing blocks to implement software radios using
    readily-available, low-cost external RF hardware and commodity processors.
    It is widely used in hobbyist, academic and commercial environments to
    support wireless communications research as well as to implement real-world
    radio systems.

    GNU Radio applications are primarily written using the Python programming
    language, while the supplied, performance-critical signal processing path
    is implemented in C++ using processor floating point extensions where
    available. Thus, the developer is able to implement real-time, high-
    throughput radio systems in a simple-to-use, rapid-application-development
    environment.

  doc_url: http://gnuradio.org/doc/doxygen/
  dev_url: http://gnuradio.org/redmine/projects/gnuradio/wiki/Development

extra:
  recipe-maintainers:
    - ryanvolz
