{% set hash = "ae93514658e8e54b2ad007ea56681c3b8d6dc441" %}
{% set version = "3.8.0.0.dev3" %}

package:
  name: gnuradio
  # 9 prefix in local version needed as hack to ensure proper ordering (after 0)
  version: {{ version }}+9g{{ hash[:7] }}

source:
  git_url: https://github.com/gnuradio/gnuradio.git
  git_rev: {{ hash }}

build:
  number: 0
  skip: True  # [win and py2k]
  run_exports:
    - {{ pin_subpackage('gnuradio', min_pin='x.x.x', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.2
    - ninja
   # below are needed to link with Qt for qtgui
   # some may be unused because of proper conda packages that get pulled in
   # (e.g. by gtk3) but keep them here as backup for the time being
    - {{ cdt('libice') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libsm') }}  # [linux]
    - {{ cdt('libx11') }}  # [linux]
    - {{ cdt('libxau') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxrender') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libuuid') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('mesa-libgl') }}  # [linux]

  host:
    - boost-cpp
    - fftw
    - libusb >=1
    - log4cpp
    - mako
    - mpir
    - numpy
    - pkg-config  # [not (win and vc<14)]
    - python
    - six
    - swig
    - volk >=1.4
  # documentation
    #- doxygen
    #- graphviz
    #- sphinx
  # testing
    #- cppunit
  # gnuradio.audio
    - alsa-lib  # [linux]
    - portaudio  # [not osx]
  # gnuradio.comedi
    #- comedi  # [linux]
  # gnuradio companion
    - gtk3  # [not win]
    - lxml  # [not win]
    - pygobject  # [not win]
    - pyyaml  # [not win]
  # gnuradio ctrlport
    - thrift
    - thrift-cpp
  # gnuradio.qtgui
    - pyqt
    - qt
    - qwt
  # gnuradio.uhd
    - uhd
  # gnuradio.video_sdl
    #- sdl2
  # gnuradio.wxgui
    - wxpython
  # gnuradio.wavelet
    - gsl
  # gnuradio.zeromq
    - cppzmq
    - zeromq

  run:
    - boost-cpp
    - {{ pin_compatible('fftw') }}
    - {{ pin_compatible('log4cpp') }}
    - mako
    - mpir
    - numpy
    - python
    - six
  # gnuradio.audio
    - {{ pin_compatible('alsa-lib') }}  # [linux]
    - {{ pin_compatible('portaudio') }}  # [not osx]
  # gnuradio.comedi
    #- {{ pin_compatible('comedi') }}  # [linux]
  # gnuradio companion
    - {{ pin_compatible('gtk3') }}  # [not win]
    - lxml  # [not win]
    - pygobject  # [not win]
    - pyyaml  # [not win]
  # gnuradio ctrlport
    - thrift
    - {{ pin_compatible('thrift-cpp', max_pin='x.x.x') }}
  # gnuradio.qtgui
    - pyqt
    - qt
    - {{ pin_compatible('qwt') }}
  # gnuradio.video_sdl
    #- {{ pin_compatible('sdl2') }}
  # gnuradio.wxgui
    - wxpython
  # gnuradio.wavelet
    - gsl
    # dep on openblas needed from linking with gsl because conda-forge gsl
    # package replaces libgslcblas with link to libopenblas
    # (to remove, check for gsl package update to include run_exports)
    - openblas  # [not win]
  # gnuradio.zeromq
    - pyzmq
    - zeromq

test:
  commands:
    - conda inspect linkages -p $PREFIX gnuradio  # [not win]
    - conda inspect objects -p $PREFIX gnuradio  # [osx]

  imports:
    - gnuradio.analog
    # FIXME: re-enable audio test when it works for python 3
    - gnuradio.audio  # [py2k]
    - gnuradio.blocks
    - gnuradio.channels
#    - gnuradio.comedi
    - gnuradio.digital
    - gnuradio.dtv
    - gnuradio.fec
    - gnuradio.fft
    - gnuradio.filter
    - gnuradio.gr
    - gnuradio.qtgui
    - gnuradio.trellis
    - gnuradio.uhd
#    - gnuradio.video_sdl
    - gnuradio.vocoder
    - gnuradio.wavelet
    - gnuradio.zeromq
    - pmt

about:
  home: http://gnuradio.org/
  license: GPL-3.0
  license_file: COPYING
  summary: 'The free and open software radio ecosystem'
  description: |
    GNU Radio is a free software development toolkit that provides the signal
    processing runtime and processing blocks to implement software radios using
    readily-available, low-cost external RF hardware and commodity processors.
    It is widely used in hobbyist, academic and commercial environments to
    support wireless communications research as well as to implement real-world
    radio systems.

    GNU Radio applications are primarily written using the Python programming
    language, while the supplied, performance-critical signal processing path
    is implemented in C++ using processor floating point extensions where
    available. Thus, the developer is able to implement real-time, high-
    throughput radio systems in a simple-to-use, rapid-application-development
    environment.

  doc_url: http://gnuradio.org/doc/doxygen/
  dev_url: http://gnuradio.org/redmine/projects/gnuradio/wiki/Development

extra:
  recipe-maintainers:
    - ryanvolz
