{% set version = "3.7.11" %}

package:
  name: gnuradio
  version: {{ version }}

source:
  url: https://gnuradio.org/releases/gnuradio/gnuradio-{{ version }}.tar.gz
  sha256: 87d9ba3183858efdbb237add3f9de40f7d65f25e16904a9bc8d764a7287252d4

build:
  number: 3
  skip: True  # [win]
  detect_binary_files_with_prefix: True

requirements:
  build:
    - boost 1.64.*
    - cheetah
    - cmake >=3.2
    - cppunit
    - fftw
    - libusb >=1
    - log4cpp
    - numpy
    - pkg-config
    - python >=2.7,<3
    - swig
    - toolchain
  # documentation
    #- doxygen
    #- graphviz
    #- sphinx
  # gnuradio.audio
    - portaudio
  # gnuradio.comedi
    #- comedi
  # gnuradio companion
    #- lxml
    #- pygtk
  # gnuradio ctrlport
    #- thrift
  # gnuradio.qtgui
    - pyqt >=4,<5
    - qwt
  # gnuradio.uhd
    - uhd 3.10.2.*
  # gnuradio.video_sdl
    #- sdl
  # gnuradio.wxgui
    - wxpython
  # gnuradio.wavelet
    #- gsl
  # gnuradio.zeromq
    #- cppzmq
    #- zeromq

  run:
    - boost 1.64.*
    - cheetah
    - fftw
    - libusb >=1
    - log4cpp
    - numpy
    - python >=2.7,<3
  # gnuradio.audio
    - portaudio
  # gnuradio.comedi
    #- comedi
  # gnuradio companion
    #- lxml
    #- pygtk
  # gnuradio ctrlport
    #- thrift
  # gnuradio.qtgui
    - pyqt >=4,<5
    - qwt
  # gnuradio.uhd
    - uhd 3.10.2.*
  # gnuradio.video_sdl
    #- sdl
  # gnuradio.wxgui
    - wxpython
  # gnuradio.wavelet
    #- gsl
  # gnuradio.zeromq
    #- pyzmq
    #- zeromq

test:
  imports:
    - gnuradio.analog
#    - gnuradio.atsc
    - gnuradio.audio  # [not osx]
    - gnuradio.blocks
    - gnuradio.channels
#    - gnuradio.comedi
    - gnuradio.digital
#    - gnuradio.dtv
#    - gnuradio.fcd
#    - gnuradio.fec
    - gnuradio.fft
    - gnuradio.filter
    - gnuradio.gr
#    - gnuradio.noaa
#    - gnuradio.pager
    - gnuradio.qtgui
#    - gnuradio.trellis
    - gnuradio.uhd
#    - gnuradio.video_sdl
#    - gnuradio.vocoder
#    - gnuradio.wavelet
    - gnuradio.wxgui
#    - gnuradio.zeromq
    - pmt

about:
  home: http://gnuradio.org/
  license: GPL-3.0
  license_file: COPYING
  summary: 'The free and open software radio ecosystem'
  description: |
    GNU Radio is a free software development toolkit that provides the signal
    processing runtime and processing blocks to implement software radios using
    readily-available, low-cost external RF hardware and commodity processors.
    It is widely used in hobbyist, academic and commercial environments to
    support wireless communications research as well as to implement real-world
    radio systems.

    GNU Radio applications are primarily written using the Python programming
    language, while the supplied, performance-critical signal processing path
    is implemented in C++ using processor floating point extensions where
    available. Thus, the developer is able to implement real-time, high-
    throughput radio systems in a simple-to-use, rapid-application-development
    environment.

  doc_url: http://gnuradio.org/doc/doxygen/
  dev_url: http://gnuradio.org/redmine/projects/gnuradio/wiki/Development

extra:
  recipe-maintainers:
    - ryanvolz
