{% set version = "3.7.12.0" %}

package:
  name: gnuradio
  version: {{ version }}

source:
#  url: https://gnuradio.org/releases/gnuradio/gnuradio-{{ version }}.tar.gz
  url: https://github.com/gnuradio/gnuradio/archive/v{{ version }}.tar.gz
  sha256: 20bb08263fb934c3474b20bd55e58b9324782b5a18cdb3f7bb5150276fcb5ceb

build:
  number: 5
  skip: True  # [win]
  run_exports:
    - {{ pin_subpackage('gnuradio', min_pin='x.x.x', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.2
    - jom  # [win]
    - ninja  # [unix]
   # below are needed to link with Qt for qtgui
    - {{ cdt('libice') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libsm') }}  # [linux]
    - {{ cdt('libx11') }}  # [linux]
    - {{ cdt('libxau') }}  # [linux]
    - {{ cdt('libxcb') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxext') }}  # [linux]
    - {{ cdt('libxfixes') }}  # [linux]
    - {{ cdt('libxrender') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libuuid') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('mesa-libgl') }}  # [linux]

  host:
    - boost
    - boost-cpp
    - cheetah
    - fftw
    - libusb >=1
    - log4cpp
    #- mako >=0.4.2  # will be required to replace Cheetah in an upcoming version
    - numpy
    - pkg-config  # [not win]
    - python
    - swig >=2.0.4
    - volk >=1.4
  # documentation
    #- doxygen
    #- graphviz
    #- sphinx
  # testing
    #- cppunit
  # gnuradio.audio
    - alsa-lib  # [linux]
    - portaudio  # [not osx]
  # gnuradio.comedi
    #- comedi  # [linux]
  # gnuradio companion
    - lxml
    #- pygtk
  # gnuradio ctrlport
    - thrift
    - thrift-cpp >=0.10,<0.11  # build errors with 0.11
  # gnuradio.qtgui
    - pyqt
    - qt
    - qwt >=5.2,<=6.2.0
  # gnuradio.uhd
    - uhd
  # gnuradio.video_sdl
    #- sdl2
  # gnuradio.wxgui
    - wxpython
  # gnuradio.wavelet
    - gsl
    # dep on openblas needed from linking with gsl because conda-forge gsl
    # package replaces libgslcblas with link to libopenblas
    # (to remove, check for gsl package update to include run_exports)
    - openblas  # [not win]
  # gnuradio.zeromq
    - cppzmq
    - zeromq

  run:
   # the pin_compatible requirements below are only needed until respective package has run_exports
    - {{ pin_compatible('boost', max_pin='x.x.x') }}
    - {{ pin_compatible('boost-cpp', max_pin='x.x.x') }}
    - cheetah
    - {{ pin_compatible('fftw') }}
    #- mako >=0.4.2  # will be required to replace Cheetah in an upcoming version
    - numpy
    - python
  # gnuradio.audio
    - {{ pin_compatible('alsa-lib') }}  # [linux]
    - {{ pin_compatible('portaudio') }}  # [not osx]
  # gnuradio.comedi
    #- {{ pin_compatible('comedi') }}  # [linux]
  # gnuradio companion
    #- lxml
    #- pygtk
  # gnuradio ctrlport
    - thrift
    - {{ pin_compatible('thrift-cpp', max_pin='x.x.x') }}
  # gnuradio.qtgui
    - {{ pin_compatible('pyqt', max_pin='x.x') }}
    - {{ pin_compatible('qt', max_pin='x.x') }}
    - {{ pin_compatible('qwt') }}
  # gnuradio.video_sdl
    #- {{ pin_compatible('sdl2') }}
  # gnuradio.wxgui
    - wxpython
  # gnuradio.wavelet
    - gsl
    # dep on openblas needed from linking with gsl because conda-forge gsl
    # package replaces libgslcblas with link to libopenblas
    # (to remove, check for gsl package update to include run_exports)
    - openblas  # [not win]
  # gnuradio.zeromq
    - pyzmq
    - {{ pin_compatible('zeromq', max_pin='x.x.x') }}

test:
  commands:
    - conda inspect linkages -p $PREFIX gnuradio  # [not win]
    - conda inspect objects -p $PREFIX gnuradio  # [osx]

  imports:
    - gnuradio.analog
    - gnuradio.atsc
    - gnuradio.audio
    - gnuradio.blocks
    - gnuradio.channels
#    - gnuradio.comedi
    - gnuradio.digital
    - gnuradio.dtv
#    - gnuradio.fcd
    - gnuradio.fec
    - gnuradio.fft
    - gnuradio.filter
    - gnuradio.gr
    - gnuradio.noaa
    - gnuradio.pager
    - gnuradio.qtgui
    - gnuradio.trellis
    - gnuradio.uhd
#    - gnuradio.video_sdl
    - gnuradio.vocoder
    - gnuradio.wavelet
    - gnuradio.wxgui
    - gnuradio.zeromq
    - pmt

about:
  home: http://gnuradio.org/
  license: GPL-3.0
  license_file: COPYING
  summary: 'The free and open software radio ecosystem'
  description: |
    GNU Radio is a free software development toolkit that provides the signal
    processing runtime and processing blocks to implement software radios using
    readily-available, low-cost external RF hardware and commodity processors.
    It is widely used in hobbyist, academic and commercial environments to
    support wireless communications research as well as to implement real-world
    radio systems.

    GNU Radio applications are primarily written using the Python programming
    language, while the supplied, performance-critical signal processing path
    is implemented in C++ using processor floating point extensions where
    available. Thus, the developer is able to implement real-time, high-
    throughput radio systems in a simple-to-use, rapid-application-development
    environment.

  doc_url: http://gnuradio.org/doc/doxygen/
  dev_url: http://gnuradio.org/redmine/projects/gnuradio/wiki/Development

extra:
  recipe-maintainers:
    - ryanvolz
