channels:
  # only used for README generation, see recipe/conda_build_config.yaml
  targets:
  - [ryanvolz, main]
github:
  user_or_org: ryanvolz
provider:
  linux: azure
  osx: azure
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: QMEYQz3c5DswOMoOq+NttUxx1xhHfspqlSZPimsllgHu+5gke9pGsFkgGM7162Xg233L018+u9u4zeGh0nBqXOobAfhsVkv+hI2M/eZvw/ST4L9cAR8VipW7XMRywMr+yn7cIacAWyYEVWLDCtfvRi//YFhsFWkc3SwKfzls5mk53vyxcnwAS61dHPVpyYThjUSN/DttfJw/HKWjlphyWbaDZBAmpsn+n94lRQr2O32z9mfK3KmVftfw5ejjzI7RkV/PjWAyEPBiMP5761ZjpkpQrZB4lqmO15iKg0GoupQd5T/3ZHiVKrPS2h9d7GhKH9xPiUI3ZAipKoX1IgQQ6avy9L9iM84YHB1N3Ie3aTqBA8ye/vvuj3aiJZtuNaDQHP6UQMuVioyfhSJa5WNpGn19sKoby4F295IlvysI7rFC9SiYSTaF4g8HBRI96+WZggFnop9dnhtVBwm0Kwnb6i1NUwEJpUwx0zOVldCCDgq88vA+3tDFiMT8Pd3tS/plSyhLs0eaED+yBUuyBpEM2qRUsgVabJHwF90FbdseETWftQmgdJjAw+2XnAqbMpX840WLBn4YG21ATm6p5xPUpZ7fCSlIOKXHBxvuEohbWGQoQhk7G96mpr6GQH1CPZIfe8Rj3YhT/9k4qmiK5iuIbj4Aw7flp21dJsbr8cQD78w=
appveyor:
  secure:
    BINSTAR_TOKEN: VdjdJuU4p0EJN2odZG5M+ig8GWMsDzxqsWLd9fhZ2IPrMPz6a4YvBRcQrbVaSDYo
azure:
  user_or_org: rvolz
